package com.quarkus.cms.media.entity;

import io.quarkus.hibernate.orm.panache.PanacheEntityBase;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

import java.time.Instant;
import java.util.ArrayList;
import java.util.List;

import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

/**
 * Media file entity representing an uploaded file in the CMS media library.
 *
 * <p>Stores file metadata (name, hash, MIME type, size, storage provider) and relationship to
 * content types. The actual file bytes are managed by the configured {@code StorageProvider}.
 */
@Entity
@Table(
    name = "cms_files",
    indexes = {
      @Index(name = "idx_files_hash", columnList = "hash"),
      @Index(name = "idx_files_provider", columnList = "provider"),
      @Index(name = "idx_files_folder_id", columnList = "folder_id"),
      @Index(name = "idx_files_created_at", columnList = "created_at")
    })
public class CmsFile extends PanacheEntityBase {

  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  public Long id;

  /** Original file name as provided by the uploader. */
  @NotBlank
  @Size(max = 255)
  @Column(nullable = false, length = 255)
  public String name;

  /** SHA-256 hash of the file content (hex-encoded). */
  @Size(max = 64)
  @Column(length = 64)
  public String hash;

  /** File extension without the dot (e.g., "jpg", "png", "pdf"). */
  @Size(max = 20)
  @Column(name = "ext", length = 20)
  public String ext;

  /** MIME type (e.g., "image/jpeg", "application/pdf"). */
  @NotBlank
  @Size(max = 127)
  @Column(name = "mime_type", nullable = false, length = 127)
  public String mimeType;

  /** File size in bytes. */
  @Column(nullable = false)
  public long size;

  /** Public URL for accessing the file (generated by the storage provider). */
  @Size(max = 2048)
  @Column(length = 2048)
  public String url;

  /** Storage provider key (e.g., "local", "s3", "r2"). */
  @NotBlank
  @Size(max = 50)
  @Column(nullable = false, length = 50)
  public String provider;

  /** Storage provider-specific file path or key. */
  @Size(max = 1024)
  @Column(name = "storage_key", length = 1024)
  public String storageKey;

  /** Alternative text for accessibility (images only). */
  @Size(max = 512)
  @Column(name = "alt_text", length = 512)
  public String altText;

  /** Caption / description. */
  @Size(max = 1024)
  @Column(length = 1024)
  public String caption;

  /** Image width in pixels (null for non-image files). */
  @Column(name = "width")
  public Integer width;

  /** Image height in pixels (null for non-image files). */
  @Column(name = "height")
  public Integer height;

  /** Optional folder ID for organizing files in the media library. */
  @Column(name = "folder_id")
  public Long folderId;

  /** Folder path for display purposes (e.g., "/images/banners"). */
  @Size(max = 1024)
  @Column(name = "folder_path", length = 1024)
  public String folderPath;

  /** Related content type UID if this file is associated with a specific content type. */
  @Size(max = 255)
  @Column(name = "related_content_type", length = 255)
  public String relatedContentType;

  /** User ID of the uploader. */
  @Column(name = "uploaded_by_id")
  public Long uploadedById;

  /** Thumbnail/formats metadata stored as JSON. */
  @JdbcTypeCode(SqlTypes.JSON)
  @Column(name = "formats", columnDefinition = "jsonb")
  public List<ImageFormatInfo> formats = new ArrayList<>();

  @Column(name = "created_at", nullable = false, updatable = false)
  public Instant createdAt = Instant.now();

  @Column(name = "updated_at", nullable = false)
  public Instant updatedAt = Instant.now();

  // ---- Named queries ----

  /** Find files by folder ID. */
  public static List<CmsFile> findByFolder(Long folderId) {
    return list("folderId = ?1 order by createdAt desc", folderId);
  }

  /** Find files by MIME type prefix (e.g., "image/"). */
  public static List<CmsFile> findByMimeTypePrefix(String prefix) {
    return list("mimeType like ?1 order by createdAt desc", prefix + "%");
  }

  /** Search files by name (case-insensitive partial match). */
  public static List<CmsFile> searchByName(String query) {
    return list("lower(name) like ?1 order by createdAt desc", "%" + query.toLowerCase() + "%");
  }

  /** Find files by hash to detect duplicates. */
  public static CmsFile findByHash(String hash) {
    return find("hash = ?1", hash).firstResult();
  }

  /** Count files in a folder. */
  public static long countByFolder(Long folderId) {
    return count("folderId", folderId);
  }

  // ---- Lifecycle callbacks ----

  @PrePersist
  protected void onCreate() {
    createdAt = Instant.now();
    updatedAt = Instant.now();
  }

  @PreUpdate
  protected void onUpdate() {
    updatedAt = Instant.now();
  }

  // ---- Inner types ----

  /**
   * Metadata for a generated image format variant (thumbnail, responsive size).
   */
  public static class ImageFormatInfo {
    /** Format name (e.g., "thumbnail", "small", "medium"). */
    public String name;

    /** Width in pixels. */
    public int width;

    /** Height in pixels. */
    public int height;

    /** File size of the variant in bytes. */
    public long size;

    /** Public URL for this variant. */
    public String url;

    /** Storage key for this variant. */
    public String storageKey;

    /** MIME type of the variant (may differ from original, e.g., WebP conversion). */
    public String mimeType;

    public ImageFormatInfo() {}

    public ImageFormatInfo(
        String name, int width, int height, long size, String url, String storageKey,
        String mimeType) {
      this.name = name;
      this.width = width;
      this.height = height;
      this.size = size;
      this.url = url;
      this.storageKey = storageKey;
      this.mimeType = mimeType;
    }
  }
}
