package com.quarkus.cms.plugin.seo;

import com.quarkus.cms.core.schema.model.FieldDefinition;
import com.quarkus.cms.core.schema.model.FieldType;
import com.quarkus.cms.plugin.CmsPlugin;
import com.quarkus.cms.plugin.PluginMetadata;
import com.quarkus.cms.plugin.PluginRegistrationContext;
import com.quarkus.cms.plugin.admin.AdminPageDefinition;
import com.quarkus.cms.plugin.admin.AdminPanelExtension;
import com.quarkus.cms.plugin.content.ContentTypeExtension;
import com.quarkus.cms.plugin.hook.HookContext;
import com.quarkus.cms.plugin.hook.PluginHook;

import io.quarkus.logging.Log;

import jakarta.enterprise.context.ApplicationScoped;

import java.util.List;
import java.util.Map;

/**
 * Example SEO plugin that demonstrates the CMS Plugin System.
 *
 * <p>This plugin:
 *
 * <ul>
 *   <li>Adds {@code metaTitle}, {@code metaDescription}, and {@code metaKeywords} fields to all
 *       content types (via {@code "*"} target)
 *   <li>Auto-generates a meta description from the first 160 characters of content if none is
 *       provided (via a lifecycle hook)
 *   <li>Registers an admin panel page for SEO settings
 *   <li>Provides a sample SEO analysis endpoint
 * </ul>
 *
 * <p>This mirrors Strapi's SEO plugin which adds meta fields to content types and provides SEO
 * analysis tools.
 */
@ApplicationScoped
public class SeoPlugin implements CmsPlugin {

  private static final PluginMetadata METADATA =
      PluginMetadata.builder("cms-seo-plugin", "1.0.0")
          .displayName("SEO Plugin")
          .description(
              "Adds SEO meta fields (meta title, description, keywords) to content types "
                  + "with auto-generated meta descriptions and an SEO analysis endpoint.")
          .author("Quarkus CMS Team")
          .license("MIT")
          .homepage("https://github.com/quarkus-cms/cms-seo-plugin")
          .options(
              Map.of(
                  "autoGenerateDescription", "true",
                  "descriptionMaxLength", "160",
                  "metaTitleMaxLength", "70"))
          .build();

  @Override
  public PluginMetadata getMetadata() {
    return METADATA;
  }

  @Override
  public void register(PluginRegistrationContext context) {
    Log.info("SEO Plugin registering...");

    // Register the SEO content type extension via context
    context.registerContentTypeExtension(new SeoContentTypeExtension());

    // Register admin page for SEO settings
    context.registerAdminPage(
        AdminPageDefinition.builder("seo")
            .displayName("SEO Settings")
            .componentPath("/plugins/seo/SettingsPage")
            .routePath("/admin/plugins/seo")
            .build());

    Log.info("SEO Plugin registered successfully");
  }

  @Override
  public void unregister() {
    Log.info("SEO Plugin unregistered");
  }

  @Override
  public List<ContentTypeExtension> getContentTypeExtensions() {
    return List.of(new SeoContentTypeExtension());
  }

  @Override
  public List<PluginHook> getHooks() {
    return List.of(new SeoLifecycleHook());
  }

  @Override
  public List<AdminPanelExtension> getAdminPanelExtensions() {
    return List.of(
        () ->
            List.of(
                AdminPageDefinition.builder("seo")
                    .displayName("SEO Settings")
                    .componentPath("/plugins/seo/SettingsPage")
                    .routePath("/admin/plugins/seo")
                    .build()));
  }

  // ---- Internal: SEO Content Type Extension ----

  /** Adds meta title, meta description, and meta keywords fields to all content types. */
  static class SeoContentTypeExtension implements ContentTypeExtension {

    @Override
    public String getTargetContentType() {
      return "*"; // Apply to all content types
    }

    @Override
    public List<FieldDefinition> getAdditionalFields() {
      return List.of(
          FieldDefinition.builder("metaTitle", FieldType.STRING)
              .required(false)
              .maxLength(70)
              .pluginOptions(
                  Map.of(
                      "cms-seo-plugin",
                      Map.of(
                          "weight", "high",
                          "autoGenerate", "false")))
              .build(),
          FieldDefinition.builder("metaDescription", FieldType.TEXT)
              .required(false)
              .maxLength(160)
              .pluginOptions(
                  Map.of(
                      "cms-seo-plugin",
                      Map.of(
                          "weight", "high",
                          "autoGenerate", "true",
                          "sourceField", "content")))
              .build(),
          FieldDefinition.builder("metaKeywords", FieldType.STRING)
              .required(false)
              .pluginOptions(Map.of("cms-seo-plugin", Map.of("weight", "medium")))
              .build());
    }

    @Override
    public Map<String, Object> getPluginOptions() {
      return Map.of(
          "cms-seo-plugin",
          Map.of(
              "autoGenerateDescription", true,
              "descriptionMaxLength", 160,
              "metaTitleMaxLength", 70));
    }
  }

  // ---- Internal: SEO Lifecycle Hook ----

  /** Auto-generates meta descriptions from content body if not provided. */
  static class SeoLifecycleHook implements PluginHook {

    @Override
    public String getHookId() {
      return "cms-seo-plugin.auto-description";
    }

    @Override
    public void beforeCreate(HookContext context) {
      autoGenerateDescription(context);
    }

    @Override
    public void beforeUpdate(HookContext context) {
      autoGenerateDescription(context);
    }

    @SuppressWarnings("unchecked")
    private void autoGenerateDescription(HookContext context) {
      if (!(context.getData() instanceof Map)) return;

      Map<String, Object> data = (Map<String, Object>) context.getData();

      // Only proceed if metaDescription is empty/null and there's content
      Object existingDesc = data.get("metaDescription");
      if (existingDesc != null && !existingDesc.toString().isBlank()) return;

      Object content = data.get("content");
      if (content == null) return;

      String text = content.toString().replaceAll("<[^>]+>", "").trim();
      if (text.isBlank()) return;

      String description = text.length() > 160 ? text.substring(0, 157) + "..." : text;
      data.put("metaDescription", description);

      Log.debugf(
          "Auto-generated meta description (%d chars) for content type: %s",
          description.length(), context.getContentType());
    }
  }
}
